Update react version to work with react 18
saleor/saleor-sdk pull request #160
Opened 2022-03-25 09:54 UTC by bmigirl

Also remove react and react dom from deps and leave it only in peer deps

2022-03-28 07:07 UTC, jwm0 requested changes

2022-03-28 07:07 UTC, jwm0 commented on package.json
> +    "react-dom": ">= 17.0.2"
I don't think react-dom is needed in the peer dependency - SDK is not using it directly

2022-03-28 07:07 UTC, jwm0 commented on package.json
> -    "react-dom": "^17.0.2",
These 2 need to stay in dev dependencies, otherwise they won't be installed and tests would fail.

2022-10-26 10:12 UTC, jonybekov commented
@bmigirl Hi, are you planning to fix the suggestions?

2023-06-14 13:29 UTC, closed without merging